<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\ShopItem;

class ShopItemSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $items = [
            [
                'name' => 'Exclude my threads from restricting image download',
                'category' => 'Feature Updates',
                'description' => 'Exclude your threads from normal image restriction settings.',
                'price' => 299.00,
                'stock' => null,
                'sold_count' => 552,
                'rating' => 5.0,
                'rating_count' => 1,
                'duration' => 'Permanent',
                'key' => 'exclude_image_restrict',
            ],
            [
                'name' => 'Image Save/Download access in all section',
                'category' => 'User Access',
                'description' => 'This will enable image save and image download feature on your account so that you can save your favorite fakes. Image download is already enabled for everyone in Hidden Subscribers section without this add on.',
                'price' => 3999.00,
                'stock' => null,
                'sold_count' => 683,
                'rating' => 2.80,
                'rating_count' => 5,
                'duration' => '1 months',
                'key' => 'image_save_access',
            ],
            [
                'name' => 'Featured thread in homepage',
                'category' => 'Promot your content',
                'description' => 'Promote your thread in featured threads slider in home page',
                'price' => 3999.00,
                'stock' => 10,
                'sold_count' => 536,
                'rating' => 4.33,
                'rating_count' => 3,
                'duration' => '1 months',
                'key' => 'featured_homepage_thread',
            ],
            [
                'name' => 'Automatic Thread Bump (One time Everyday)',
                'category' => 'Promot your content',
                'description' => 'Automatically bumps your selected thread once every day to keep it active and visible.',
                'price' => 999.00,
                'stock' => null,
                'sold_count' => 205,
                'rating' => 1.0,
                'rating_count' => 1,
                'duration' => '1 months',
                'key' => 'auto_thread_bump',
            ],
            [
                'name' => 'Thread Highlight',
                'category' => 'Promot your content',
                'description' => 'Highlight your thread title in lists to make it stand out from other threads.',
                'price' => 1499.00,
                'stock' => null,
                'sold_count' => 364,
                'rating' => 5.0,
                'rating_count' => 2,
                'duration' => '1 months',
                'key' => 'thread_highlight',
            ],
            [
                'name' => 'Direct link to your profile (Ex:- desifakes/user)',
                'category' => 'Feature Updates',
                'description' => 'Get a shortened direct vanity URL redirecting to your profile page.',
                'price' => 500.00,
                'stock' => null,
                'sold_count' => 111,
                'rating' => 3.50,
                'rating_count' => 4,
                'duration' => 'Permanent',
                'key' => 'direct_profile_link',
            ],
            [
                'name' => 'Access to run private threads for subscribers',
                'category' => 'User Access',
                'description' => 'Allows you to create and manage private subscriber-only threads.',
                'price' => 2000.00,
                'stock' => null,
                'sold_count' => 193,
                'rating' => 5.0,
                'rating_count' => 1,
                'duration' => '1 months',
                'key' => 'private_threads_access',
            ],
            [
                'name' => 'Username Change',
                'category' => 'User Access',
                'description' => 'Allows you to change your username on the forum.',
                'price' => 5000.00,
                'stock' => null,
                'sold_count' => 190,
                'rating' => 4.0,
                'rating_count' => 1,
                'duration' => 'One-time',
                'key' => 'username_change',
            ],
            [
                'name' => 'Profile Highlight',
                'category' => 'Feature Updates',
                'description' => 'Highlight your Profile Postbit with any colour effect to stand out from the crowd !!!',
                'price' => 2999.00,
                'stock' => 50,
                'sold_count' => 165,
                'rating' => 5.0,
                'rating_count' => 1,
                'duration' => 'Permanent',
                'key' => 'profile_highlight',
            ],
            [
                'name' => 'Username Style',
                'category' => 'Feature Updates',
                'description' => 'Add username colour, shadow, and other styles to make your profile name stand out.',
                'price' => 1999.00,
                'stock' => null,
                'sold_count' => 303,
                'rating' => 4.67,
                'rating_count' => 3,
                'duration' => 'Permanent',
                'key' => 'username_style',
            ],
            [
                'name' => 'Remove Account Restrictions',
                'category' => 'User Access',
                'description' => 'Remove account restrictions due to receiving warnings or penalties.',
                'price' => 4999.00,
                'stock' => null,
                'sold_count' => 28,
                'rating' => 0.0,
                'rating_count' => 0,
                'duration' => 'One-time',
                'key' => 'remove_restrictions',
            ],
            [
                'name' => 'Sticky Thread',
                'category' => 'Promot your content',
                'description' => 'Pin your thread on top of the first page of the forum',
                'price' => 3999.00,
                'stock' => 10,
                'sold_count' => 758,
                'rating' => 5.0,
                'rating_count' => 4,
                'duration' => '1 months',
                'key' => 'sticky_thread',
            ],
            [
                'name' => 'Thread Title Style',
                'category' => 'Promot your content',
                'description' => 'Highlight your thread title with bold letters, any color, shadow, and glow effect for more attention!!!',
                'price' => 1999.00,
                'stock' => 50,
                'sold_count' => 348,
                'rating' => 5.0,
                'rating_count' => 6,
                'duration' => '1 months',
                'key' => 'thread_title_style',
            ],
            [
                'name' => 'yourname@desifakes.com email alias',
                'category' => 'Feature Updates',
                'description' => 'Get a professional email alias redirecting to your personal email address.',
                'price' => 39000.00,
                'stock' => 10,
                'sold_count' => 3,
                'rating' => 5.0,
                'rating_count' => 1,
                'duration' => 'Permanent',
                'key' => 'email_alias',
            ],
        ];

        foreach ($items as $item) {
            ShopItem::updateOrCreate(['key' => $item['key']], $item);
        }
    }
}
